# Generated by Django 2.0.5 on 2019-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('szgbidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='szgb',
            name='url',
            field=models.URLField(default=1, max_length=32, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
