# Generated by Django 2.0.5 on 2019-01-29 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('szgbidding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='szgb',
            options={'verbose_name_plural': '政采网信息'},
        ),
    ]
