# Generated by Django 2.0.5 on 2019-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('szgbidding', '0002_szgb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='search_keyword',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标签'),
        ),
    ]
