# Generated by Django 2.0.5 on 2019-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('szgbidding', '0003_keyword_search_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szgb',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
